using System.Net.Http;
using System.Text.Json.Nodes;

using Pi.Ai;
using Pi.Telemetry;

namespace Pi.AgentCore;

/// <summary>How multiple tool calls from one assistant response are scheduled.</summary>
public enum ToolExecutionMode
{
    /// <summary>Prepare and execute each call before starting the next.</summary>
    Sequential,

    /// <summary>Prepare calls in source order and execute them concurrently.</summary>
    Parallel,
}

/// <summary>How queued messages are drained at a loop boundary.</summary>
public enum QueueMode
{
    /// <summary>Drain every queued message.</summary>
    All,

    /// <summary>Drain only the oldest queued message.</summary>
    OneAtATime,
}

/// <summary>Delegate used to start one provider-neutral assistant stream.</summary>
public delegate AssistantMessageEventStream AgentStreamFunction(
    Model model,
    Context context,
    SimpleStreamOptions? options = null);

/// <summary>Delegate that converts the agent transcript to provider messages.</summary>
public delegate ValueTask<IReadOnlyList<Message>> AgentMessageConverter(IReadOnlyList<Message> messages);

/// <summary>Delegate that transforms the transcript before conversion.</summary>
public delegate ValueTask<IReadOnlyList<Message>> AgentContextTransformer(
    IReadOnlyList<Message> messages,
    CancellationToken cancellationToken);

/// <summary>Delegate that receives one agent lifecycle event.</summary>
public delegate ValueTask AgentEventSink(AgentEvent @event, CancellationToken cancellationToken);

/// <summary>Delegate used to execute a tool call.</summary>
public delegate Task<AgentToolResult> AgentToolExecutor(
    string toolCallId,
    JsonObject arguments,
    CancellationToken cancellationToken,
    Action<AgentToolResult>? onUpdate);

/// <summary>Delegate used to prepare raw tool arguments before schema validation.</summary>
public delegate JsonObject AgentToolArgumentPreparer(JsonObject arguments);

/// <summary>Result returned by the before-tool-call interception hook.</summary>
public sealed record BeforeToolCallResult
{
    /// <summary>Prevents the tool from executing.</summary>
    public bool Block { get; init; }

    /// <summary>Text placed in the blocked tool result.</summary>
    public string? Reason { get; init; }

    /// <summary>Requests termination after this result when every result agrees.</summary>
    public bool Terminate { get; init; }
}

/// <summary>Partial field-level override returned by the after-tool-call hook.</summary>
public sealed record AfterToolCallResult
{
    /// <summary>Replacement result content.</summary>
    public IReadOnlyList<ContentBlock>? Content { get; init; }

    /// <summary>Replacement structured details.</summary>
    public JsonNode? Details { get; init; }

    /// <summary>Replacement error status.</summary>
    public bool? IsError { get; init; }

    /// <summary>Replacement tool usage.</summary>
    public Usage? Usage { get; init; }

    /// <summary>Replacement termination hint.</summary>
    public bool? Terminate { get; init; }
}

/// <summary>Context passed to the before-tool-call hook.</summary>
public sealed record BeforeToolCallContext
{
    /// <summary>Assistant response that requested the tool.</summary>
    public required AssistantMessage AssistantMessage { get; init; }

    /// <summary>Raw tool call block.</summary>
    public required ToolCall ToolCall { get; init; }

    /// <summary>Validated, mutable argument object.</summary>
    public required JsonObject Arguments { get; init; }

    /// <summary>Current agent context.</summary>
    public required AgentContext Context { get; init; }
}

/// <summary>Context passed to the after-tool-call hook.</summary>
public sealed record AfterToolCallContext
{
    /// <summary>Assistant response that requested the tool.</summary>
    public required AssistantMessage AssistantMessage { get; init; }

    /// <summary>Raw tool call block.</summary>
    public required ToolCall ToolCall { get; init; }

    /// <summary>Validated argument object used for execution.</summary>
    public required JsonObject Arguments { get; init; }

    /// <summary>Executed result before overrides.</summary>
    public required AgentToolResult Result { get; init; }

    /// <summary>Whether the execution is currently treated as an error.</summary>
    public required bool IsError { get; init; }

    /// <summary>Current agent context.</summary>
    public required AgentContext Context { get; init; }
}

/// <summary>Context supplied after a completed assistant turn.</summary>
public sealed record ShouldStopAfterTurnContext
{
    /// <summary>Completed assistant message.</summary>
    public required AssistantMessage Message { get; init; }

    /// <summary>Tool results generated by this turn.</summary>
    public required IReadOnlyList<ToolResultMessage> ToolResults { get; init; }

    /// <summary>Current context after the turn.</summary>
    public required AgentContext Context { get; init; }

    /// <summary>Messages returned by this loop invocation.</summary>
    public required IReadOnlyList<Message> NewMessages { get; init; }
}

/// <summary>Replacement state selected before the next assistant turn.</summary>
public sealed record AgentLoopTurnUpdate
{
    /// <summary>Replacement context, or null to retain the current context.</summary>
    public AgentContext? Context { get; init; }

    /// <summary>Replacement model, or null to retain the current model.</summary>
    public Model? Model { get; init; }

    /// <summary>Replacement reasoning level, or null to retain the configured level.</summary>
    public string? ThinkingLevel { get; init; }
}

/// <summary>Agent context presented to the low-level loop.</summary>
public sealed class AgentContext
{
    /// <summary>System prompt included in provider requests.</summary>
    public string SystemPrompt { get; init; } = string.Empty;

    /// <summary>Ordered transcript visible to the model.</summary>
    public IReadOnlyList<Message> Messages { get; init; } = [];

    /// <summary>Tools available for this run.</summary>
    public IReadOnlyList<AgentTool> Tools { get; init; } = [];

    internal List<Message> MessagesInternal { get; init; } = [];

    internal List<AgentTool> ToolsInternal { get; init; } = [];
}

/// <summary>Final or partial output produced by a tool.</summary>
public sealed record AgentToolResult
{
    /// <summary>Text or image content returned to the model.</summary>
    public IReadOnlyList<ContentBlock> Content { get; init; } = [];

    /// <summary>Structured details retained for UI and logs.</summary>
    public JsonNode? Details { get; init; } = new JsonObject();

    /// <summary>Tool-local usage, when available.</summary>
    public Usage? Usage { get; init; }

    /// <summary>Names of tools made available by this result.</summary>
    public IReadOnlyList<string>? AddedToolNames { get; init; }

    /// <summary>Requests termination after this tool batch.</summary>
    public bool Terminate { get; init; }
}

/// <summary>Tool definition consumed by the agent runtime.</summary>
public sealed class AgentTool
{
    /// <summary>Stable tool name used in assistant tool calls.</summary>
    public required string Name { get; init; }

    /// <summary>Human-readable label for UI display.</summary>
    public required string Label { get; init; }

    /// <summary>Tool description sent to the model.</summary>
    public required string Description { get; init; }

    /// <summary>JSON Schema for tool arguments.</summary>
    public JsonNode Parameters { get; init; } = new JsonObject();

    /// <summary>Optional provider-side constrained sampling configuration.</summary>
    public ConstrainedSamplingConfig? ConstrainedSampling { get; init; }

    /// <summary>Optional raw-argument preparation hook.</summary>
    public AgentToolArgumentPreparer? PrepareArguments { get; init; }

    /// <summary>Tool execution callback.</summary>
    public required AgentToolExecutor Execute { get; init; }

    /// <summary>Per-tool scheduling override.</summary>
    public ToolExecutionMode? ExecutionMode { get; init; }
}

/// <summary>Low-level loop configuration.</summary>
public sealed class AgentLoopConfig
{
    /// <summary>Explicit parent context for provider telemetry.</summary>
    public TelemetryContext? TelemetryContext { get; init; }

    /// <summary>Explicit provider API key.</summary>
    public string? ApiKey { get; init; }

    /// <summary>Optional custom request function.</summary>
    public Func<HttpRequestMessage, CancellationToken, Task<HttpResponseMessage>>? Fetch { get; init; }

    /// <summary>Provider-scoped environment overrides.</summary>
    public IReadOnlyDictionary<string, string>? Environment { get; init; }

    /// <summary>Payload callback forwarded to the provider.</summary>
    public Func<JsonNode?, Model, ValueTask<JsonNode?>>? OnPayload { get; init; }

    /// <summary>Response callback forwarded to the provider.</summary>
    public Func<ProviderResponse, Model, ValueTask>? OnResponse { get; init; }

    /// <summary>Custom provider request headers.</summary>
    public IReadOnlyDictionary<string, string?>? Headers { get; init; }

    /// <summary>Provider request timeout in milliseconds.</summary>
    public int? TimeoutMs { get; init; }

    /// <summary>Maximum provider retry attempts.</summary>
    public int? MaxRetries { get; init; }

    /// <summary>Maximum provider retry delay.</summary>
    public int? MaxRetryDelayMs { get; init; }

    /// <summary>Sampling temperature.</summary>
    public double? Temperature { get; init; }

    /// <summary>Additional sampling parameters.</summary>
    public IReadOnlyDictionary<string, JsonNode?>? SamplingParameters { get; init; }

    /// <summary>Maximum provider output tokens.</summary>
    public int? MaxTokens { get; init; }

    /// <summary>Preferred provider transport.</summary>
    public string? Transport { get; init; }

    /// <summary>Prompt-cache retention.</summary>
    public string? CacheRetention { get; init; }

    /// <summary>Provider cache/session identifier.</summary>
    public string? SessionId { get; init; }

    /// <summary>WebSocket connection timeout.</summary>
    public int? WebSocketConnectTimeoutMs { get; init; }

    /// <summary>Provider-neutral metadata.</summary>
    public IReadOnlyDictionary<string, JsonNode?>? Metadata { get; init; }

    /// <summary>Provider-neutral tool selection.</summary>
    public string? ToolChoice { get; init; }

    /// <summary>Requested reasoning level.</summary>
    public string? Reasoning { get; init; }

    /// <summary>Whether a deferred response is requested.</summary>
    public bool Deferred { get; init; }

    /// <summary>Deferred response window.</summary>
    public string? DeferredWindow { get; init; }

    /// <summary>Custom reasoning budgets.</summary>
    public ThinkingBudgets? ThinkingBudgets { get; init; }

    /// <summary>Model used for the next provider request.</summary>
    public required Model Model { get; init; }

    /// <summary>Converts the agent transcript to provider messages.</summary>
    public AgentMessageConverter ConvertToLlm { get; init; } = static messages => new(messages);

    /// <summary>Optional transcript transform before conversion.</summary>
    public AgentContextTransformer? TransformContext { get; init; }

    /// <summary>Resolves a provider API key for each request.</summary>
    public Func<string, ValueTask<string?>>? GetApiKey { get; init; }

    /// <summary>Stops after a completed turn when it returns true.</summary>
    public Func<ShouldStopAfterTurnContext, ValueTask<bool>>? ShouldStopAfterTurn { get; init; }

    /// <summary>Supplies replacement context/model state before continuing.</summary>
    public Func<ShouldStopAfterTurnContext, ValueTask<AgentLoopTurnUpdate?>>? PrepareNextTurn { get; init; }

    /// <summary>Returns steering messages to inject before the next provider request.</summary>
    public Func<ValueTask<IReadOnlyList<Message>>>? GetSteeringMessages { get; init; }

    /// <summary>Returns follow-up messages after the agent would otherwise stop.</summary>
    public Func<ValueTask<IReadOnlyList<Message>>>? GetFollowUpMessages { get; init; }

    /// <summary>Default scheduling mode for tool batches.</summary>
    public ToolExecutionMode ToolExecution { get; init; } = ToolExecutionMode.Parallel;

    /// <summary>Runs before an allowed tool executes.</summary>
    public Func<BeforeToolCallContext, CancellationToken, ValueTask<BeforeToolCallResult?>>? BeforeToolCall { get; init; }

    /// <summary>Runs after a tool executes and may replace result fields.</summary>
    public Func<AfterToolCallContext, CancellationToken, ValueTask<AfterToolCallResult?>>? AfterToolCall { get; init; }
}

/// <summary>Mutable context-owned agent state.</summary>
public sealed class AgentState
{
    private IReadOnlyList<AgentTool> _tools = [];
    private IReadOnlyList<Message> _messages = [];

    /// <summary>System prompt used for future turns.</summary>
    public string SystemPrompt { get; set; } = string.Empty;

    /// <summary>Model used for future turns.</summary>
    public Model Model { get; set; } = AgentDefaults.UnknownModel;

    /// <summary>Requested reasoning level.</summary>
    public string ThinkingLevel { get; set; } = ThinkingLevels.Off;

    /// <summary>Available tools. Assignments copy the top-level collection.</summary>
    public IReadOnlyList<AgentTool> Tools
    {
        get => _tools;
        set => _tools = value?.ToArray() ?? throw new ArgumentNullException(nameof(value));
    }

    /// <summary>Conversation transcript. Assignments copy the top-level collection.</summary>
    public IReadOnlyList<Message> Messages
    {
        get => _messages;
        set => _messages = value?.ToArray() ?? throw new ArgumentNullException(nameof(value));
    }

    /// <summary>True while a run, including awaited listeners, is active.</summary>
    public bool IsStreaming { get; internal set; }

    /// <summary>Partial streamed assistant message, when one exists.</summary>
    public Message? StreamingMessage { get; internal set; }

    /// <summary>Tool-call ids currently executing.</summary>
    public IReadOnlySet<string> PendingToolCalls { get; internal set; } = new HashSet<string>(StringComparer.Ordinal);

    /// <summary>Error from the most recent failed or aborted turn.</summary>
    public string? ErrorMessage { get; internal set; }
}

/// <summary>Base class for agent lifecycle events.</summary>
public abstract record AgentEvent
{
    /// <summary>Upstream-compatible event discriminator.</summary>
    public abstract string Type { get; }
}

/// <summary>Agent run started.</summary>
public sealed record AgentStartEvent : AgentEvent
{
    /// <inheritdoc />
    public override string Type => "agent_start";
}

/// <summary>Agent run ended.</summary>
public sealed record AgentEndEvent(IReadOnlyList<Message> Messages) : AgentEvent
{
    /// <inheritdoc />
    public override string Type => "agent_end";
}

/// <summary>Assistant turn started.</summary>
public sealed record TurnStartEvent : AgentEvent
{
    /// <inheritdoc />
    public override string Type => "turn_start";
}

/// <summary>Assistant turn ended.</summary>
public sealed record TurnEndEvent(
    AssistantMessage Message,
    IReadOnlyList<ToolResultMessage> ToolResults) : AgentEvent
{
    /// <inheritdoc />
    public override string Type => "turn_end";
}

/// <summary>Message lifecycle start.</summary>
public sealed record MessageStartEvent(Message Message) : AgentEvent
{
    /// <inheritdoc />
    public override string Type => "message_start";
}

/// <summary>Assistant partial message update.</summary>
public sealed record MessageUpdateEvent(
    Message Message,
    AssistantMessageEvent AssistantMessageEvent) : AgentEvent
{
    /// <inheritdoc />
    public override string Type => "message_update";
}

/// <summary>Message lifecycle end.</summary>
public sealed record MessageEndEvent(Message Message) : AgentEvent
{
    /// <inheritdoc />
    public override string Type => "message_end";
}

/// <summary>Tool execution started.</summary>
public sealed record ToolExecutionStartEvent(
    string ToolCallId,
    string ToolName,
    JsonObject Arguments) : AgentEvent
{
    /// <inheritdoc />
    public override string Type => "tool_execution_start";
}

/// <summary>Tool execution progress update.</summary>
public sealed record ToolExecutionUpdateEvent(
    string ToolCallId,
    string ToolName,
    JsonObject Arguments,
    AgentToolResult PartialResult) : AgentEvent
{
    /// <inheritdoc />
    public override string Type => "tool_execution_update";
}

/// <summary>Tool execution ended.</summary>
public sealed record ToolExecutionEndEvent(
    string ToolCallId,
    string ToolName,
    AgentToolResult Result,
    bool IsError) : AgentEvent
{
    /// <inheritdoc />
    public override string Type => "tool_execution_end";
}

/// <summary>Small defaults shared by Agent and tests.</summary>
public static class AgentDefaults
{
    /// <summary>Fallback model used when no initial state was supplied.</summary>
    public static Model UnknownModel { get; } = new()
    {
        Id = "unknown",
        Name = "unknown",
        Api = "unknown",
        Provider = "unknown",
        BaseUrl = string.Empty,
        Reasoning = false,
        Input = [],
        ContextWindow = 0,
        MaxTokens = 0,
    };
}
